# -*- coding: utf-8 -*-
"""Translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1it7USreY03iIpsfknvVIo9sYg_6FaNrt
"""

# --- Diagnostic Test Block ---

print("Installing required library...")
!pip install -q google-generativeai
print("✅ Library installed.")

import google.generativeai as genai

# -----------------------------------------------------------------
# ⬇ *** PASTE THE SAME GEMINI API KEY YOU HAVE BEEN USING HERE *** ⬇
# -----------------------------------------------------------------
YOUR_GEMINI_API_KEY = "API key"

print("\n--- Running Diagnostic Test ---")

try:
    if "PASTE_YOUR_API_KEY_HERE" in YOUR_GEMINI_API_KEY:
        raise ValueError("Please paste your actual Gemini API Key to run the test.")

    genai.configure(api_key=YOUR_GEMINI_API_KEY)

    print("✅ API key configured. Attempting to list available models...")

    # This is the test: We ask Google what models are available for your key.
    model_list = list(genai.list_models())

    if not model_list:
        print("\n--- ❌ RESULT: FAILED ---")
        print("Diagnosis: Your API key is configured, but it has no access to any models.")
        print("This strongly indicates the 'Generative Language API' is NOT enabled in the correct Google Cloud project.")
        print("Please carefully repeat the steps to enable it for the project linked to your key.")
    else:
        print("\n--- ✅ RESULT: SUCCESS (PARTIAL) ---")
        print("Diagnosis: Your API key IS WORKING and can see the following models:")

        found_flash_model = False
        for m in model_list:
            # We are looking for a model that can be used for translation.
            if 'generateContent' in m.supported_generation_methods:
                print(f"  - {m.name}")
                if 'gemini-1.5-flash' in m.name:
                    found_flash_model = True

        print("\n--- FINAL DIAGNOSIS ---")
        if found_flash_model:
            print("✅ Your API key has access to 'gemini-1.5-flash'. The configuration is correct.")
            print("The previous error is very unusual. Please try running the original translation code one more time.")
        else:
            print("❌ Your API key works, but it CANNOT see 'gemini-1.5-flash'.")
            print("This could be due to regional restrictions or a temporary issue.")
            print("Let's try the original code again, but with a different model: 'gemini-pro'.")

except Exception as e:
    print("\n--- ❌ RESULT: FAILED ---")
    print(f"Diagnosis: The test failed with an error: {e}")
    print("This confirms a fundamental problem with your API key or project setup.")
    print("The most reliable solution is to create a brand new key in a new project from the Google AI Studio page.")

# --- Block 1: Install Library and Get Ready ---
print("Installing the Google Generative AI library...")
!pip install -q google-generativeai
print("✅ Library installed.")

import google.generativeai as genai
import os

# --- Block 2: Configure the Gemini API ---

# -----------------------------------------------------------------
# ⬇ *** PASTE YOUR GEMINI API KEY HERE *** ⬇
# -----------------------------------------------------------------
YOUR_GEMINI_API_KEY = "AIzaSyBsUgqRyS4asRueLbksC1bVp3lkrDPqPAQ"

# Configure the Gemini client
try:
    if "PASTE_YOUR_API_KEY_HERE" in YOUR_GEMINI_API_KEY:
        raise ValueError("Please paste your actual Gemini API Key into the 'YOUR_GEMINI_API_KEY' variable.")

    genai.configure(api_key=YOUR_GEMINI_API_KEY)

    # --- THIS IS THE FIX: We are using a model that your key has access to ---
    model = genai.GenerativeModel('gemini-2.5-pro')

    print("✅ Gemini model ('gemini-pro') configured and ready for translation.")

except Exception as e:
    print(f"❌ Error configuring Gemini: {e}")
    model = None

# --- Block 3: Define the Translation Function ---

def translate_romanized_to_english(text_to_translate):
    """
    Uses the Gemini API to translate Romanized text into English.
    """
    if not text_to_translate or not text_to_translate.strip():
        return "No text provided to translate."

    print("\nSending text to Gemini for translation...")
    prompt = f"""
    Translate the following text into clear, natural-sounding English.
    The text is from a different language but is typed using English letters (Romanized text).
    Provide only the final English translation.

    Original Text: "{text_to_translate}"
    English Translation:
    """
    try:
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"An error occurred during translation: {e}")
        return "Error during translation."

# --- Block 4: Get Input and Translate (Runs only once) ---

def run_single_translation():
    """
    Gets one input from the user, translates it, and then stops.
    """
    if model is None:
        print("\n❌ Cannot start translator. Please re-check your API key.")
        return

    print("\n\n--- Romanized Text to English Translator ---")
    print("Enter text from any language using English letters.")

    # Get input from the user just one time
    user_input = input("\nEnter Text > ")

    # Translate the input and print the result
    english_translation = translate_romanized_to_english(user_input)

    print(f"\nEnglish: {english_translation}")
    print("\n--- Program finished ---")

# --- Start the program ---
run_single_translation()

